project:
  type: website
  output-dir: docs

website:
  title: "Jaime Orrego Oñate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV

format:
  html:
    theme: solar
    toc: true

editor: visual
